let valor: any;
valor = "olá";
console.log(valor);
valor = 42;
console.log(valor);
valor = true;
console.log(valor);
valor = {nome: "joão", idade: 30};
console.log(valor);
valor = [1, 2, 3];
console.log(valor);